### ISSUE TITLE
The DB2 pod security policy  does not work  

### ISSUE THREAD

**Issue by vcailly** [kubernetes-in-the-enterprise/portfolio-database#1]
I am trying to deploy the application on an IBM IVP 3.1.0 platform and the install of the install of the DB2 helm charts fails to deploy properly the Statefullset  into the  "stock-trader-data" namespace 
It looks like that the  "db2-pod-security-policy" is not working.   

Notice that i can deploy successfully into the "default" namespace  but not in the  "stock-trader-data" namespace.  
When deploying in the default namespace, using the command   _kubectl get pod stocktrade-ibm-db2oltp-dev-0 -o yaml | egrep "psp|privileged"_ , we can see that  the "privileged" policy is applied.

**Below the results when using the Yaml files  published in this git repository**

**[vcailly@localhost stocktrader]$ kubectl describe StatefulSet stocktrade-ibm-db2oltp-dev | egrep "event|Reason|FailedCreate|------"**
  Type     Reason        Age                From                    Message
  ----     ------        ----               ----                    -------
  Warning  FailedCreate  16m (x4 over 19m)  statefulset-controller  create Pod stocktrade-ibm-db2oltp-dev-0 in StatefulSet stocktrade-ibm-db2oltp-dev failed error: pods "stocktrade-ibm-db2oltp-dev-0" is forbidden: unable to validate against any pod security policy: [spec.securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used capabilities.add: Invalid value: "SYS_RESOURCE": capability may not be added capabilities.add: Invalid value: "IPC_OWNER": capability may not be added capabilities.add: Invalid value: "SYS_NICE": capability may not be added spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
  Warning  FailedCreate  4m (x38 over 19m)  statefulset-controller  create Pod stocktrade-ibm-db2oltp-dev-0 in StatefulSet stocktrade-ibm-db2oltp-dev failed error: pods "stocktrade-ibm-db2oltp-dev-0" is forbidden: unable to validate against any pod security policy: [spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used capabilities.add: Invalid value: "SYS_RESOURCE": capability may not be added capabilities.add: Invalid value: "IPC_OWNER": capability may not be added capabilities.add: Invalid value: "SYS_NICE": capability may not be added]
[vcailly@localhost stocktrader]$ 

**below  the Kubectl and Helm versions I am using**

[vcailly@localhost stocktrader]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1+icp", GitCommit:"90febef3a98de5efb2e1248525e24a57e01ad386", GitTreeState:"clean", BuildDate:"2018-09-04T08:03:44Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

[vcailly@localhost stocktrader]$ helm version --tls
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1+icp", GitCommit:"843201eceab24e7102ebb87cb00d82bc973d84a7", GitTreeState:"clean"}
[vcailly@localhost stocktrader]$

**Comment by mdelder** [comment]
In Kubernetes 1.11, the ClusterRoleBinding for `db2-privileges-cluster-role`, change the `apiGroups: ['policy']` to `apiGroups: ['extensions']` and it will resolve this issue.

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: db2-privileges-cluster-role
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - db2-privileges
```

As you make the change, you can validate the change using the following command:

```
kubectl --as=system:serviceaccount:stock-trader-data:default \
   auth can-i use podsecuritypolicies/db2-privileges
```
.. which will return a simple "yes" or "no" answer.

**Comment by vcailly** [comment]
Thanks Mickael . Yes it fixes the problem
